### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by tyrius02** [i80and/fett#4]
setup.py indicates the MIT open source license is applicable to this package, but there isn't an actual LICENSE file here.

I'd like to build a feedstock for conda-forge as this package is an upstream dependency for another package (I'm also building a feedstock for). Unfortunately, the conda-forge people won't accept the feedstock without a license file.

The MIT license is pretty boiler-plate. I can create a pull request that introduces the file if you'd like.

**Comment by maresb** [comment]
ping @i80and

**Comment by i80and** [comment]
Merged -- Sorry about the delay

**Comment by maresb** [comment]
No worries, thanks @i80and!
